### PR TITLE
Send verification options

### PR DESCRIPTION
**Pull request by tselouie**
temporary fix...
if user doesnt exist in database
**Current:**
-window pops up
-redirects to form
**Supposed to be:**
-input css changes to invalid(resolved)
-invalid-feedback shows up(resolved)
-stopPropagation

**Problem:**
unable to send value
Missing a boolean value to be accessed in Signup Validation

### CODE REVIEW

**Comment by lucacataldo** [comment]
Just pulled this from your branch and it doesn't seem to be working rn

**Comment by lucacataldo** [comment]
What's this one trying to accomplish? The signup issue if there's a duplicate user?

**Comment by lucacataldo** [comment]
Possibly handled via #102

**Comment by tselouie** [comment]
> What's this one trying to accomplish? The signup issue if there's a duplicate user?

Sort of the opposite. forgot password needs to identify that the user exists before sending the email.

I also wanted the error not as an 'alert' but as css is-invalid

**Comment by tselouie** [comment]
> Just pulled this from your branch and it doesn't seem to be working rn

what is not working? the main fxn of the branch is to deal with forgot password

**Comment by lucacataldo** [comment]
Oh sorry i think I misunderstood what you were trying to do my bad, it probably wasn't broken then. You might be able to look at my code for the implementation of the duplicate email and use that to accomplish what you were trying to do. Let me test out what you have again cause it could be on the right track

**Comment by tselouie** [comment]
Honestly idk wth i'm doing on signupvalidation, i may need u to walk through it with me... For the time being we can **discard all my changes on SignupValidation**. Everything else should be good to merge.

**Pull request merged**
