### PR TITLE
moved files to views, deleted html and subfolders

### PR DESCRIPTION
**Pull request by gko5**

### CODE REVIEW

**Comment by lucacataldo** [comment]
> 
> 
> Looks good, but under "Files changed" i noticed it says a submodule was added, was this intentional? Not too sure what that is lol

It actually looks like maybe you cloned the eezcommerce repo into the repository itself, we need to fix that before we merge otherwise it'll cause a whole bunch of git issues. You should be able to delete that extra eezcommerce folder via `git rm -r eezcommerce` (make sure your deleting the right one) and then push up to the same `fix-folders` branch on your origin which should update here

**Comment by lucacataldo** [comment]
Actually, I'm going to be putting up a PR polishing / cleaning things up plus getting Handlebars set up which will be moving folders around anyways, so maybe we hand hold off on this for a bit.

**Comment by gko5** [comment]
oh thats super weird. I'll reclone my fork again. Let me know when its ok to fix the folders again

**Comment by lucacataldo** [comment]
closing via #58

**Pull request closed without merging**
